CREATE TABLE products
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    price DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);